---
- name: Modify variables in init file
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ item.option}}=.*'
    line: '{{ item.option }}="{{ item.value }}"'
    state: present
  with_items: "{{ jenkins_init_changes }}"
  register: jenkins_init

- name: Immediately restart Jenkins on init config changes.
  service: name=jenkins state=restarted
  when: jenkins_init.changed

- name: Trigger handlers immediately in case Jenkins was installed
  meta: flush_handlers
