---
# Variable setup.
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define jenkins_repo_url
  set_fact:
    jenkins_repo_url: "{{ __jenkins_repo_url }}"
  when: jenkins_repo_url is not defined

- name: Define jenkins_repo_key_url
  set_fact:
    jenkins_repo_key_url: "{{ __jenkins_repo_key_url }}"
  when: jenkins_repo_key_url is not defined

- name: Define jenkins_pkg_url
  set_fact:
    jenkins_pkg_url: "{{ __jenkins_pkg_url }}"
  when: jenkins_pkg_url is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# System common
- name: Ensure extended resource limits
  pam_limits:
    domain: jenkins
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "nofile", type: "soft", value: "4096" }
    - { key: "nofile", type: "hard", value: "8192" }
    - { key: "nproc", type: "soft", value: "30654" }
    - { key: "nproc", type: "hard", value: "30654" }

- name: Cron task for cleaning old logs every 2 weeks on Sunday
# TODO: split non-jenkins related cron (nginx)
  cron:
    name: Delete old logs
    minute: "*"
    hour: "8"
    weekday: "0"
    job: "find {{ item }} -mtime +14 -type f -delete"
    user: "root"
  with_items:
    - "/var/log/jenkins"
    - "/var/log/nginx"
  tags:
    - disk-cleanup
